### ISSUE TITLE
The current github action for linting does not specify Python version (and of other dependencies)

### ISSUE THREAD

**Issue by jangop** [danielgatis/rembg#409]
Currently, for linting, https://github.com/danielgatis/rembg/blob/9d2cca1f4d02efd569191c28875dd4318f003b25/.github/workflows/lint_python.yml is used. For convenience, let me include the file's contents here:

```yaml
name: Lint

on: [pull_request, push]

jobs:
    lint_python:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-python@v2
            - run: pip install --upgrade pip wheel
            - run: pip install bandit black flake8 flake8-bugbear flake8-comprehensions isort safety mypy
            - run: mypy --install-types --non-interactive --ignore-missing-imports ./rembg
            - run: bandit --recursive --skip B101,B104,B310,B311,B303 --exclude ./rembg/_version.py ./rembg
            - run: black --force-exclude rembg/_version.py --check --diff ./rembg
            - run: flake8 ./rembg --count --ignore=B008,C901,E203,E266,E731,F401,F811,F841,W503 --max-line-length=120 --show-source --statistics --exclude ./rembg/_version.py
            - run: isort --check-only --profile black ./rembg
            - run: safety check
```

This action has a number of problems. Versions are either not specified or outdated. The biggest problem is surely that the version of Python is not specified. Recently, it changed from Python 3.10 to Python 3.11 with this setup, which has led to dependency issues (some package not being available for 3.11, yet; the details do not necessarily matter).

The actions `actions/checkout` and `actions/setup-python` have younger versions available.

`bandit`,  `black`,  `flake8`,  `flake8-bugbear`, `flake8-comprehensions`, `isort`, `safety`, `mypy` are all installed but their versions are not specified.

Why is all this problematic? The “build” may change from one moment to the next. You commit one thing to this repo and some new version of some tool complains about something entirely unrelated to your change. See #400.

@danielgatis I see you are busy with other things, but I can do most of the legwork on this.
