### ISSUE TITLE
How to cite this repository?

### ISSUE THREAD

**Issue by abhishek47kashyap** [danielgatis/rembg#726]
The references section mentions [U2Net](https://github.com/xuebinqin/U-2-Net) and [pymatting](https://github.com/pymatting/pymatting) but I would like to cite this repository directly. Could I get a BibTeX for this repository?

According to this `academia.stackexchange` [answer](https://academia.stackexchange.com/a/172780/142490), simply having a `CITATION.cff` in the repository should make GitHub produce a citation widget. Here's one for this repo, if you want to use it:
```
cff-version: 1.2.0
title: rembg
message: Rembg is a tool to remove images background
type: software
authors:
  - given-names: Daniel
    family-names: Gatis
    email: danielgatis@gmail.com
identifiers:
  - type: url
    value: 'https://github.com/danielgatis'
repository-code: 'https://github.com/danielgatis/rembg'
url: 'https://github.com/danielgatis/rembg'
abstract: Rembg is a tool to remove images background.
license: MIT
commit: 9079508935ae55d6eefa0fd75f870599640e8593
version: 2.0.63
date-released: '2025-02-21'
```
